### PR TITLE
chore: support laravel 6.0

### PR DESCRIPTION
**Pull request by atymic**
- drop 5.6 support
- bump versions of phpunit
- support newer testbench
- update changelog
- fix linting issues

### CODE REVIEW

**Comment by ahmedash95** [comment]
Thanks a lot for taking the time to do that. may I ask if the FB-API is working with u or it needs to be updated?

**Comment by atymic** [comment]
I haven't actually tested it since I don't have a facebook page. @dwightwatson said he might jump in and help maintain/update the channel.

**Comment by dwightwatson** [comment]
I'll have some time during the week to have a play - I saw some other issues on the repo suggesting that maybe it's not actually compatible with Facebook's latest API.

I don't think there's any harm in just merging in Laravel 6.0 support and moving forward to fix incompatibilities separately.

**Comment by dwightwatson** [comment]
Just jumping on this now - looks like it can't be installed with Laravel 6.1.0.

I wonder if it's a matter of changing the constraint from ~6.0 to ^6.0?

**Comment by atymic** [comment]
`~6.0` should match any `6.x.x`
https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

Can you post the install log? Maybe there's another issue.

**Comment by dwightwatson** [comment]
I thought it was odd, but then I was perhaps mistaken about how constraints worked.

Just realised it hasn't been tagged as a new version, so just using `dev-master`. Thanks!

**Comment by atymic** [comment]
Oops, good catch. I've tagged as `1.6.0` :)

**Comment by dwightwatson** [comment]
Cool, just tested and this is working (and posting) for me.

**Pull request merged**
